name: Integrated Test

on:
  push:
    branches:
      - master
      - next
  pull_request:

jobs:
  react-vite-preview-protocol:
    runs-on: ubuntu-24.04
    timeout-minutes: 15

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v6
      - name: Use Node.js 22.18.0
        uses: actions/setup-node@v4
        with:
          node-version: 22.18.0
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - run: pnpm install --frozen-lockfile
      - run: pnpm build
      - run: pnpm e2e
